services:
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./conf:/etc/nginx/conf.d/
      - ./wiki:/usr/share/nginx/wiki
      - ./html:/usr/share/nginx/html
      - ./certs:/usr/share/nginx/certs
    ports:
      - 443:443
    depends_on:
      - fpm

  fpm:
    image: php:fpm
    restart: always
    ports:
      - ":9000"
    volumes:
      - ./wiki:/usr/share/nginx/wiki

  gitea:
    image: gitea/gitea:1.21.10
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    volumes:
      - gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"

volumes:
  gitea:
    driver: local
