services:
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./conf:/etc/nginx/conf.d/
      - ./wiki:/usr/share/nginx/wiki
      - ./html:/usr/share/nginx/html
      - ./certs:/usr/share/nginx/certs
    ports:
      - 443:443
    depends_on:
      - fpm

  fpm:
    image: php:fpm
    restart: always
    ports:
      - ":9000"
    volumes:
      - ./wiki:/usr/share/nginx/wiki

  forgejo:
    image: codeberg.org/forgejo/forgejo:7
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    volumes:
      - forgejo:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ":3000"

  opengist:
    image: ghcr.io/thomiceli/opengist:1.7
    restart: always
    environment:
      - OG_CUSTOM_LOGO=logo.png
      - OG_CUSTOM_FAVICON=logo.png
      - OG_SSH_GIT_ENABLED=false
    ports:
      - ":6157" # HTTP port
    volumes:
      - "./opengist:/opengist"
    
volumes:
  forgejo:
    driver: local
